swagger: "2.0"
info:
  description: "REST API for social distancing app"
  version: "1.0.0"
  title: "Social Distance App"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "socialdistance.io"
basePath: "/api/v1"
schemes:
- "https"
- "http"
paths:
  /appSessions/{id}/locations:
    post:
      tags:
      - "location"
      summary: "Adds location data"
      description: ""
      operationId: "addLocation"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of pet to return"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "Location object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/Location"
      responses:
        "405":
          description: "Invalid input"
definitions:
  Location:
    type: "object"
    required:
    - "lan"
    - "log"
    properties:
      lan:
        type: "string"
        example: "123.4444555"
      log:
        type: "string"
        example: "123.4444555"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"